UPDATE locations SET branch_id = 1, submitter_id = 5 WHERE name = 'TDN Kranggan';
UPDATE locations SET branch_id = 1, submitter_id = 1 WHERE name = 'KSN KRANGGAN';
UPDATE locations SET branch_id = 1, submitter_id = 4 WHERE name = 'GROSIR KRANGGAN';
UPDATE locations SET branch_id = 1, submitter_id = 6 WHERE name = 'HO LT 1 KRANGGAN';
UPDATE locations SET branch_id = 2, submitter_id = 1 WHERE name = 'KSN DEPOK';
UPDATE locations SET branch_id = 2, submitter_id = 4 WHERE name = 'GROSIR DEPOK';
UPDATE locations SET branch_id = 3, submitter_id = 5 WHERE name = 'TDN Jati Rawamangun';
UPDATE locations SET branch_id = 3, submitter_id = 6 WHERE name = 'Kedai Jati Rawamangun';
UPDATE locations SET branch_id = 3, submitter_id = 4 WHERE name = 'GROSIR - JTR / RAWAMANGUN';
UPDATE locations SET branch_id = 4, submitter_id = 5 WHERE name = 'TDN Duri Kosambi';
UPDATE locations SET branch_id = 4, submitter_id = 1 WHERE name = 'KSN KOSAMBI';
UPDATE locations SET branch_id = 4, submitter_id = 4 WHERE name = 'GROSIR - KSB / DURI KOSAMBI';
UPDATE locations SET branch_id = 5, submitter_id = 6 WHERE name = 'Delta 2 Cikarang';
UPDATE locations SET branch_id = 6, submitter_id = 1 WHERE name = 'KSN CIKAMPEK';
UPDATE locations SET branch_id = 6, submitter_id = 4 WHERE name = 'GROSIR - CKP / CIKAMPEK';
UPDATE locations SET branch_id = 7, submitter_id = 6 WHERE name = 'HO (Semua Lantai & Basement)';
UPDATE locations SET branch_id = 7, submitter_id = 6 WHERE name = 'LT 4';
UPDATE locations SET branch_id = 7, submitter_id = 5 WHERE name = 'TDN Tebet';
UPDATE locations SET branch_id = 7, submitter_id = 2 WHERE name = 'NUSTRO TEBET';
UPDATE locations SET branch_id = 7, submitter_id = 4 WHERE name = 'GROSIR SPM / TEBET';
UPDATE locations SET branch_id = 8, submitter_id = 6 WHERE name = 'KEDAI BANDUNG';
UPDATE locations SET branch_id = 9, submitter_id = 5 WHERE name = 'TDN Kranji';
UPDATE locations SET branch_id = 9, submitter_id = 4 WHERE name = 'GROSIR - KRJ / KRANJI';
UPDATE locations SET branch_id = 10, submitter_id = 5 WHERE name = 'TDN Kemang';
UPDATE locations SET branch_id = 10, submitter_id = 2 WHERE name = 'NUTRO KEMANG';
UPDATE locations SET branch_id = 10, submitter_id = 4 WHERE name = 'GROSIR - KMG';
UPDATE locations SET branch_id = 11, submitter_id = 5 WHERE name = 'TDN Ceger';
UPDATE locations SET branch_id = 12, submitter_id = 5 WHERE name = 'TDN Matraman';
UPDATE locations SET branch_id = 12, submitter_id = 6 WHERE name = 'Kedai Matraman';
UPDATE locations SET branch_id = 12, submitter_id = 4 WHERE name = 'GROSIR - MTM / MATRAMAN';
UPDATE locations SET branch_id = 13, submitter_id = 5 WHERE name = 'TDN Karawaci';
UPDATE locations SET branch_id = 13, submitter_id = 6 WHERE name = 'Kedai Karawaci';
UPDATE locations SET branch_id = 13, submitter_id = 4 WHERE name = 'GROSIR - KWC / KARAWACI';
UPDATE locations SET branch_id = 14, submitter_id = 5 WHERE name = 'TDN Purwokerto';
UPDATE locations SET branch_id = 14, submitter_id = 6 WHERE name = 'Kedai Purwokerto';
UPDATE locations SET branch_id = 14, submitter_id = 4 WHERE name = 'Grosir Purwokerto';
UPDATE locations SET branch_id = 15, submitter_id = 5 WHERE name = 'TDN Semarang';
UPDATE locations SET branch_id = 15, submitter_id = 6 WHERE name = 'Kedai Semarang';
UPDATE locations SET branch_id = 15, submitter_id = 4 WHERE name = 'GROSIR - SMG / SEMARANG';
UPDATE locations SET branch_id = 16, submitter_id = 5 WHERE name = 'TDN Bogor';
UPDATE locations SET branch_id = 16, submitter_id = 4 WHERE name = 'GROSIR - BOG / BOGOR';
UPDATE locations SET branch_id = 17, submitter_id = 5 WHERE name = 'TDN Cibinong';
UPDATE locations SET branch_id = 18, submitter_id = 5 WHERE name = 'TDN Cileungsi';
UPDATE locations SET branch_id = 24, submitter_id = 5 WHERE name = 'TDN Kebagusan';
UPDATE locations SET branch_id = 26, submitter_id = 5 WHERE name = 'TDN Tanjung Duren';
UPDATE locations SET branch_id = 29, submitter_id = 5 WHERE name = 'TDN Graha 71 Bintaro';